"""FastAPI backend for the TextToSQL React UI with SSE pipeline events."""

from __future__ import annotations

import json
import queue
import threading
import uuid
from typing import Any

import pandas as pd
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from plotly.graph_objects import Figure as PlotlyFigure
from pydantic import BaseModel

from copilot_utils import (
    CODER2,
    CODER_AVAILABLE_FUNCTIONS2,
    CODER_FUNCTIONS_SPEC2,
    Smart_Agent,
    extract_sql_query,
)
from runtime import RuntimeContext, set_runtime
from visualization_utils import chart_display_payload, table_display_payload

app = FastAPI(title="TextToSQL API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

INIT_MESSAGE = (
    "Hello, I am your AI Analytic Assistant. Ask me anything about the Northwind database."
)

SAMPLE_QUESTIONS = [
    "What were the total sales for each year available in the database?",
    "Who are the top 5 customers by order volume, and what is the total number of orders for each?",
    "What are the top 10 most popular products based on quantity sold?",
    "What are the total sales broken down by country?",
]

_sessions: dict[str, dict[str, Any]] = {}


class ChatRequest(BaseModel):
    message: str
    session_id: str | None = None
    show_internal_thoughts: bool = False


class ClearRequest(BaseModel):
    session_id: str


def _serialize_display_data(data: Any) -> dict | None:
    if data is None:
        return None
    if isinstance(data, pd.DataFrame):
        displays = [table_display_payload(data)]
        chart = chart_display_payload(data)
        if chart:
            displays.append(chart)
        return displays
    if isinstance(data, PlotlyFigure):
        from plotly.io import to_json as plotly_to_json
        return {
            "type": "chart",
            "format": "plotly",
            "data": plotly_to_json(data),
            "chartKind": "custom",
            "autoGenerated": False,
        }
    return {"type": "text", "data": str(data)}


def _flatten_displays(items: list) -> list[dict]:
    flat: list[dict] = []
    for item in items:
        if isinstance(item, list):
            flat.extend(item)
        elif item:
            flat.append(item)
    return flat


def _augment_displays(displays: list[dict]) -> list[dict]:
    """Add auto charts for table-only results when visualization is possible."""
    if any(d.get("type") == "chart" for d in displays):
        return displays

    augmented: list[dict] = []
    for display in displays:
        augmented.append(display)
        if display.get("type") != "table":
            continue
        columns = display.get("columns") or []
        rows = display.get("rows") or []
        if not columns or not rows:
            continue
        df = pd.DataFrame(rows, columns=columns)
        chart = chart_display_payload(df)
        if chart:
            augmented.append(chart)
    return augmented


def _get_or_create_session(session_id: str | None) -> tuple[str, dict[str, Any]]:
    if session_id and session_id in _sessions:
        return session_id, _sessions[session_id]

    new_id = session_id or str(uuid.uuid4())
    agent = Smart_Agent(
        persona=CODER2,
        functions_list=CODER_AVAILABLE_FUNCTIONS2,
        functions_spec=CODER_FUNCTIONS_SPEC2,
        init_message=INIT_MESSAGE,
    )
    agent.run(user_input=None)
    _sessions[new_id] = {
        "agent": agent,
        "history": agent.conversation,
        "displays": [],
    }
    return new_id, _sessions[new_id]


@app.get("/api/health")
def health():
    return {"status": "ok"}


@app.get("/api/sample-questions")
def sample_questions():
    return {"questions": SAMPLE_QUESTIONS}


@app.post("/api/clear")
def clear_session(req: ClearRequest):
    _sessions.pop(req.session_id, None)
    return {"ok": True}


@app.post("/api/chat")
def chat(req: ChatRequest):
    if not req.message.strip():
        raise HTTPException(status_code=400, detail="Message cannot be empty")

    session_id, session = _get_or_create_session(req.session_id)
    event_queue: queue.Queue = queue.Queue()
    displays: list[dict] = []

    def on_event(event_type: str, payload: dict):
        event_queue.put({"type": event_type, **payload})

    def on_display(display_payload: dict):
        displays.append(display_payload)
        event_queue.put({"type": "display", "display": display_payload})

    runtime = RuntimeContext(
        on_display=on_display,
        show_internal_thoughts=req.show_internal_thoughts,
    )

    def run_agent():
        set_runtime(runtime)
        try:
            agent: Smart_Agent = session["agent"]
            agent.on_event = on_event
            _, code, history, answer, data = agent.run(
                user_input=req.message,
                conversation=session["history"],
                stream=False,
            )
            session["history"] = history
            session["displays"] = displays

            serialized_displays = _augment_displays(
                _flatten_displays(
                    displays
                    or [
                        d
                        for v in data.values()
                        for d in (_serialize_display_data(v),)
                        if d is not None
                    ]
                )
            )
            sql = extract_sql_query(code) if code else None

            event_queue.put({
                "type": "done",
                "session_id": session_id,
                "answer": answer,
                "code": code,
                "sql": sql,
                "displays": serialized_displays,
            })
        except Exception as exc:
            event_queue.put({"type": "error", "detail": str(exc)})
        finally:
            set_runtime(None)
            event_queue.put(None)

    thread = threading.Thread(target=run_agent, daemon=True)
    thread.start()

    def event_stream():
        while True:
            item = event_queue.get()
            if item is None:
                break
            yield f"data: {json.dumps(item, default=str)}\n\n"

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )
