"""FastAPI backend for the Analytic Copilot React UI with SSE pipeline events."""

from __future__ import annotations

import json
import queue
import threading
import uuid
from typing import Any, Optional

import pandas as pd
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from plotly.graph_objects import Figure as PlotlyFigure
from pydantic import BaseModel, Field

from copilot_utils import (
    CODER2,
    CODER_AVAILABLE_FUNCTIONS2,
    CODER_FUNCTIONS_SPEC2,
    Smart_Agent,
    extract_sql_query,
)
from evaluation import extract_agent_sql, load_cases, score_case
from guardrails import (
    GuardrailType,
    any_blocked,
    evaluate_question,
    get_store,
    mark_soft_rules_applied,
    prompt_addons,
)
from runtime import RuntimeContext, set_runtime
from visualization_utils import chart_display_payload, table_display_payload

app = FastAPI(title="Analytic Copilot API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

INIT_MESSAGE = (
    "Hello, I am your AI Analytic Assistant. Ask me anything about the Northwind database."
)

SAMPLE_QUESTIONS = [
    "What were the total sales for each year available in the database?",
    "Who are the top 5 customers by order volume, and what is the total number of orders for each?",
    "What are the top 10 most popular products based on quantity sold?",
    "What are the total sales broken down by country?",
]

_sessions: dict[str, dict[str, Any]] = {}


class ChatRequest(BaseModel):
    message: str
    session_id: str | None = None
    show_internal_thoughts: bool = False
    attached_guardrail_ids: list[str] = Field(default_factory=list)


class ClearRequest(BaseModel):
    session_id: str


class GuardrailUpsertRequest(BaseModel):
    id: Optional[str] = None
    name: str
    type: GuardrailType
    description: str = ""
    config: dict[str, Any] = Field(default_factory=dict)


def _serialize_display_data(data: Any) -> dict | None:
    if data is None:
        return None
    if isinstance(data, pd.DataFrame):
        displays = [table_display_payload(data)]
        chart = chart_display_payload(data)
        if chart:
            displays.append(chart)
        return displays
    if isinstance(data, PlotlyFigure):
        from plotly.io import to_json as plotly_to_json
        return {
            "type": "chart",
            "format": "plotly",
            "data": plotly_to_json(data),
            "chartKind": "custom",
            "autoGenerated": False,
        }
    return {"type": "text", "data": str(data)}


def _flatten_displays(items: list) -> list[dict]:
    flat: list[dict] = []
    for item in items:
        if isinstance(item, list):
            flat.extend(item)
        elif item:
            flat.append(item)
    return flat


def _augment_displays(displays: list[dict]) -> list[dict]:
    """Add auto charts for table-only results when visualization is possible."""
    if any(d.get("type") == "chart" for d in displays):
        return displays

    augmented: list[dict] = []
    for display in displays:
        augmented.append(display)
        if display.get("type") != "table":
            continue
        columns = display.get("columns") or []
        rows = display.get("rows") or []
        if not columns or not rows:
            continue
        df = pd.DataFrame(rows, columns=columns)
        chart = chart_display_payload(df)
        if chart:
            augmented.append(chart)
    return augmented


def _get_or_create_session(session_id: str | None) -> tuple[str, dict[str, Any]]:
    if session_id and session_id in _sessions:
        return session_id, _sessions[session_id]

    new_id = session_id or str(uuid.uuid4())
    agent = Smart_Agent(
        persona=CODER2,
        functions_list=CODER_AVAILABLE_FUNCTIONS2,
        functions_spec=CODER_FUNCTIONS_SPEC2,
        init_message=INIT_MESSAGE,
    )
    agent.run(user_input=None)
    _sessions[new_id] = {
        "agent": agent,
        "history": agent.conversation,
        "displays": [],
        "attached_guardrail_ids": [],
    }
    return new_id, _sessions[new_id]


@app.get("/api/health")
def health():
    return {"status": "ok"}


@app.get("/api/sample-questions")
def sample_questions():
    return {"questions": SAMPLE_QUESTIONS}


@app.get("/api/guardrails")
def list_guardrails():
    return {"guardrails": [g.to_dict() for g in get_store().list()]}


@app.post("/api/guardrails")
def upsert_guardrail(req: GuardrailUpsertRequest):
    try:
        g = get_store().upsert(
            guardrail_id=req.id,
            name=req.name,
            type=req.type,
            description=req.description,
            config=req.config,
        )
    except Exception as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    return {"guardrail": g.to_dict()}


@app.delete("/api/guardrails/{guardrail_id}")
def delete_guardrail(guardrail_id: str):
    try:
        ok = get_store().delete(guardrail_id)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    if not ok:
        raise HTTPException(status_code=404, detail="Guardrail not found")
    return {"ok": True}


@app.post("/api/clear")
def clear_session(req: ClearRequest):
    _sessions.pop(req.session_id, None)
    return {"ok": True}


@app.get("/api/eval/cases")
def list_eval_cases():
    return {"cases": [c.to_dict() for c in load_cases()]}


@app.post("/api/eval/run")
def run_evaluation():
    """Run the golden-set harness; stream per-case results via SSE."""
    cases = load_cases()
    if not cases:
        raise HTTPException(status_code=404, detail="No evaluation cases found")

    event_queue: queue.Queue = queue.Queue()

    def run_eval():
        passed = 0
        failed = 0
        try:
            event_queue.put({"type": "eval_start", "total": len(cases)})
            for index, case in enumerate(cases):
                event_queue.put(
                    {
                        "type": "case_start",
                        "id": case.id,
                        "question": case.question,
                        "index": index,
                        "total": len(cases),
                        "notes": case.notes,
                        "gold_sql": case.gold_sql,
                    }
                )

                agent_sql: str | None = None
                try:
                    agent = Smart_Agent(
                        persona=CODER2,
                        functions_list=CODER_AVAILABLE_FUNCTIONS2,
                        functions_spec=CODER_FUNCTIONS_SPEC2,
                        init_message=INIT_MESSAGE,
                    )
                    # Fresh agent per case; no chat history, no guardrails
                    set_runtime(
                        RuntimeContext(
                            show_internal_thoughts=False,
                            attached_guardrails=[],
                            on_event=None,
                            guardrail_prompt_addon="",
                        )
                    )
                    agent.run(user_input=None)
                    _, code, _, _, _ = agent.run(
                        user_input=case.question,
                        conversation=agent.conversation,
                        stream=False,
                    )
                    agent_sql = extract_agent_sql(code) or (
                        extract_sql_query(code) if code else None
                    )
                    result = score_case(case, agent_sql)
                except Exception as exc:
                    result = score_case(case, agent_sql)
                    result.status = "error"
                    result.detail = f"Agent run failed: {exc}"
                finally:
                    set_runtime(None)

                if result.status == "passed":
                    passed += 1
                else:
                    failed += 1

                event_queue.put({"type": "case_result", **result.to_dict()})

            event_queue.put(
                {
                    "type": "eval_done",
                    "passed": passed,
                    "failed": failed,
                    "total": len(cases),
                }
            )
        except Exception as exc:
            event_queue.put({"type": "error", "detail": str(exc)})
        finally:
            set_runtime(None)
            event_queue.put(None)

    thread = threading.Thread(target=run_eval, daemon=True)
    thread.start()

    def event_stream():
        while True:
            item = event_queue.get()
            if item is None:
                break
            yield f"data: {json.dumps(item, default=str)}\n\n"

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )


@app.post("/api/chat")
def chat(req: ChatRequest):
    if not req.message.strip():
        raise HTTPException(status_code=400, detail="Message cannot be empty")

    session_id, session = _get_or_create_session(req.session_id)
    session["attached_guardrail_ids"] = list(req.attached_guardrail_ids or [])
    attached = get_store().get_many(session["attached_guardrail_ids"])
    addon = prompt_addons(attached)

    event_queue: queue.Queue = queue.Queue()
    displays: list[dict] = []

    def on_event(event_type: str, payload: dict):
        event_queue.put({"type": event_type, **payload})

    def on_display(display_payload: dict):
        displays.append(display_payload)
        event_queue.put({"type": "display", "display": display_payload})

    runtime = RuntimeContext(
        on_display=on_display,
        show_internal_thoughts=req.show_internal_thoughts,
        attached_guardrails=attached,
        on_event=on_event,
        guardrail_prompt_addon=addon,
    )

    def run_agent():
        set_runtime(runtime)
        try:
            # Pipeline stage: Guardrails
            on_event(
                "step_start",
                {
                    "step": "guardrails",
                    "label": "Applying guardrails",
                    "detail": (
                        f"{len(attached)} guardrail(s) attached"
                        if attached
                        else "No guardrails attached"
                    ),
                },
            )

            topic_results = evaluate_question(req.message, attached, on_event=on_event)
            mark_soft_rules_applied(attached, on_event=on_event)

            if any_blocked(topic_results):
                blocked = next(r for r in topic_results if r.status == "blocked")
                answer = (
                    f"I can't help with that request because the **{blocked.name}** "
                    f"guardrail blocked it.\n\n{blocked.detail}"
                )
                on_event(
                    "step_error",
                    {"step": "guardrails", "detail": blocked.detail},
                )
                event_queue.put(
                    {
                        "type": "done",
                        "session_id": session_id,
                        "answer": answer,
                        "code": None,
                        "sql": None,
                        "displays": [],
                        "guardrail_blocked": True,
                    }
                )
                return

            on_event(
                "step_complete",
                {
                    "step": "guardrails",
                    "detail": (
                        f"Passed pre-checks · {len(attached)} active"
                        if attached
                        else "Skipped (none attached)"
                    ),
                },
            )

            agent: Smart_Agent = session["agent"]
            agent.on_event = on_event
            _, code, history, answer, data = agent.run(
                user_input=req.message,
                conversation=session["history"],
                stream=False,
            )
            session["history"] = history
            session["displays"] = displays

            serialized_displays = _augment_displays(
                _flatten_displays(
                    displays
                    or [
                        d
                        for v in data.values()
                        for d in (_serialize_display_data(v),)
                        if d is not None
                    ]
                )
            )
            sql = extract_sql_query(code) if code else None

            event_queue.put({
                "type": "done",
                "session_id": session_id,
                "answer": answer,
                "code": code,
                "sql": sql,
                "displays": serialized_displays,
            })
        except Exception as exc:
            event_queue.put({"type": "error", "detail": str(exc)})
        finally:
            set_runtime(None)
            event_queue.put(None)

    thread = threading.Thread(target=run_agent, daemon=True)
    thread.start()

    def event_stream():
        while True:
            item = event_queue.get()
            if item is None:
                break
            yield f"data: {json.dumps(item, default=str)}\n\n"

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )
