export type PipelineStepId =
  | "understand"
  | "plan"
  | "context"
  | "generate"
  | "execute"
  | "respond";

export type StepStatus = "idle" | "active" | "complete" | "error";

export interface PipelineStep {
  id: PipelineStepId;
  label: string;
  description: string;
  status: StepStatus;
  detail?: string;
  code?: string;
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  displays?: DisplayPayload[];
  sql?: string | null;
  code?: string;
}

export interface DisplayPayload {
  type: "table" | "chart" | "text";
  format?: "plotly" | "matplotlib";
  columns?: string[];
  rows?: Record<string, string>[];
  data?: string;
  chartKind?: string;
  title?: string;
  autoGenerated?: boolean;
}

export type ResultViewMode = "auto" | "chart" | "table" | "both";

export interface StreamEvent {
  type: string;
  step?: PipelineStepId;
  label?: string;
  detail?: string;
  code?: string;
  assumptions?: string;
  answer?: string;
  sql?: string | null;
  session_id?: string;
  displays?: DisplayPayload[];
  display?: DisplayPayload;
}

export const PIPELINE_STEPS: Omit<PipelineStep, "status" | "detail" | "code">[] = [
  {
    id: "understand",
    label: "Understand",
    description: "Parse natural language question",
  },
  {
    id: "plan",
    label: "Plan",
    description: "Choose analyst persona & strategy",
  },
  {
    id: "context",
    label: "Context",
    description: "Retrieve schemas, tables & business rules",
  },
  {
    id: "generate",
    label: "Generate",
    description: "Write SQL + Python analysis code",
  },
  {
    id: "execute",
    label: "Execute",
    description: "Run query against SQLite & render viz",
  },
  {
    id: "respond",
    label: "Respond",
    description: "Summarize insights for the user",
  },
];
